import { twMerge } from 'tailwind-merge'

import type { Metadata } from 'next'
import { Fira_Code as FiraCode, Ubuntu } from 'next/font/google'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { IPROJECT } from '@/types/enum'

import './globals.css'

const ubuntu = Ubuntu({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-ubuntu',
})

const firaCode = FiraCode({
  subsets: ['latin'],
  variable: '--font-firacode-mono',
})

export const metadata: Metadata = {
  title: IPROJECT.name,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  return (
    <html lang={locale}>
      <body
        className={twMerge(
          ubuntu.className,
          ubuntu.variable,
          firaCode.variable,
        )}
      >
        <Header locale={locale} />

        <main className="h-main-full bg-base-200 p-6">
          <div className="h-full rounded-2xl bg-base-100 p-8">{children}</div>
        </main>

        <Footer />
      </body>
    </html>
  )
}
